LANG_JSON_DATA = {
	'input_placeholder': 'Insert a movie title, actor, genre...',
	'content-container': 'Select the source you want to watch on',
	'cancel': 'Cancel',
	'watch': 'Watch Now',
	'movies': 'Movies',
	'tvshows': 'TV Shows',
	'provider-title' : 'Provider Title',
	'rent' : 'Rent from $3.99(HD)',
	'popup-title': 'Watch Options',
	'director':'Director',
	'cast':'Cast',
	'description':'description',
	'available-on':'Available on',
    'exit-confirm':'Exit Application?',
    'exit':'Exit',
    'video1':'Video 1',
    'video2':'Video 2',
    'video3':'Video 3'
};
films = [
  		{
  			"id": 1,
  			"title": "It",
  			"cast": ["Jaeden Martell", "Jeremy Ray Taylor"],
  			"genre": ["Horror"],
  			"year": 2017,
  			"director": "Andy Muschietti",
  			"duration": "2h 15min",
  			"rating": "R",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
  		},
  		{
  			"id": 2,
  			"title": "Avatar",
  			"cast": ["Sam Worthington", "Zoe Saldana"],
  			"genre": ["Action", "Adventure", "Fantasy"],
  			"year": 2009,
  			"director": "James Cameron",
  			"duration": "2h 42min",
  			"rating": "PG-13",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
  		},
  		{
  			"id": 3,
  			"title": "Joker",
  			"cast": ["Joaquin Phoenix", "Robert De Niro"],
  			"genre": ["Crime", "Drama", "Thriller"],
  			"year": 2019,
  			"director": "Todd Phillips",
  			"duration": "2h 2min",
  			"rating": "R",
  			"plot": "Description description description description description description description description description description description description description..",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
  		},
  		{
  			"id": 4,
  			"title": "Titanic",
  			"cast": ["Leonardo DiCaprio", "Kate Winslet"],
  			"genre": ["Drama", "Romance"],
  			"year": 1997,
  			"director": "James cameron",
  			"duration": "3h 14min",
  			"rating": "PG-13",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
  		},
  		{
  			"id": 5,
  			"title": "Coraline",
  			"cast": ["Dakota Fanning", "Teri Hatcher"],
  			"genre": ["Animated", "Drama", "Family"],
  			"year": 2009,
  			"director": "Henry Selick",
  			"duration": "1h 40min",
  			"rating": "PG",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
  		},
  		{
  			"id": 6,
  			"title": "Once Upon a Time... in Hollywood",
  			"cast": ["Leonardo DiCaprio", "Brad Pitt"],
  			"genre": ["Comedy", "Drama"],
  			"year": 2019,
  			"director": "Quentin Tarantino",
  			"duration": "2h 41min",
  			"rating": "R",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
  		},
  		{
  			"id": 7,
  			"title": "A Quiet Place",
  			"cast": ["Emily Blunt", "John Krasinski"],
  			"genre": ["Drama", "Horror", "Science fiction"],
  			"year": 2018,
  			"director": "John Krasinski",
  			"duration": "1h 30min",
  			"rating": "PG-13",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
  		},
  		{
  			"id": 8,
  			"title": "Dunkirk",
  			"cast": ["Fionn Whitehead", "Barry Keoghan"],
  			"genre": ["Action", "Drama", "History"],
  			"year": 2017,
  			"director": "Christopher Nolan",
  			"duration": "1h 46min",
  			"rating": "PG-13",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
  		},
  		{
  			"id": 9,
  			"title": "The Irishman",
  			"cast": ["Robert De Niro", "Al Pacino", "Joe Pesci"],
  			"genre": ["Biography", "Crime", "Drama"],
  			"year": 2019,
  			"director": "Martin Scorsese",
  			"duration": "3h 39min",
  			"rating": "R",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
  		},
  		{
  			"id": 10,
  			"title": "Afterschool",
  			"cast": ["Ezra Miller", "Jeremy Allen White"],
  			"genre": ["Drama", "Mystery"],
  			"year": 2008,
  			"director": "Antonio Campos",
  			"duration": "2h",
  			"rating": "Not Rated",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
  		},
  		{
  			"id": 11,
  			"title": "Dark",
  			"cast": ["Louis Hofmann", "Karoline Eichhorn"],
  			"genre": ["Crime", "Drama", "Mystery"],
  			"year": 2017,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-MA",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
  		},
  		{
  			"id": 12,
  			"title": "Game of Thrones",
  			"cast": ["Louis Hofmann", "Karoline Eichhorn"],
  			"genre": ["Action", "Adventure", "Drama"],
  			"year": 2011,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-MA",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
  		},
  		{
  			"id": 13,
  			"title": "Breaking Bad",
  			"cast": ["Bryan Cranston", "Aaron Paul"],
  			"genre": ["Crime", "Drama", "Thriller"],
  			"year": 2008,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-MA",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
  		},
  		{
  			"id": 14,
  			"title": "Supernatural",
  			"cast": ["Jared Padalecki", "Jensen Ackles"],
  			"genre": ["Drama", "Fantasy", "Horror"],
  			"year": 2005,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-14",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
  		},
  		{
  			"id": 15,
  			"title": "The Flash",
  			"cast": ["Grant Gustin, Candice Patton"],
  			"genre": ["Action", "Adventure", "Drama"],
  			"year": 2014,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-PG",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
  		},
  		{
  			"id": 16,
  			"title": "Gotham",
  			"cast": ["Ben McKenzie", "Jada Pinkett Smith"],
  			"genre": ["Action", "Crime", "Drama"],
  			"year": 2014,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-14",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
  		},
  		{
  			"id": 17,
  			"title": "Homeland",
  			"cast": ["Claire Danes", "Mandy Patinkin"],
  			"genre": ["Crime", "Drama", "Mystery"],
  			"year": 2011,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-MA",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
  		},
  		{
  			"id": 18,
  			"title": "Star Trek: Discovery",
  			"cast": ["Soneque Martin-Green", "Doung Jones"],
  			"genre": ["Action", "Adventure"],
  			"year": 2017,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-14",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
  		},
  		{
  			"id": 19,
  			"title": "Ozark",
  			"cast": ["Jason Bateman", "Laura Linney"],
  			"genre": ["Drama", "Suspense"],
  			"year": 2017,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-MA",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
		},
  		{
  			"id": 20,
  			"title": "The Witcher",
  			"cast": ["Henry Cavill", "Freya Allan"],
  			"genre": ["Action", "Adventure"],
  			"year": 2019,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-MA",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
		},
  		{
  			"id": 21,
  			"title": "Bombshell",
  			"cast": ["Margot Robbie", "Nicole Kidman"],
  			"genre": ["Drama", "Biography"],
  			"year": 2019,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "R",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
		},
  		{
  			"id": 22,
  			"title": "Gremlins",
  			"cast": ["Zach Galligan", "Phoebe Cates"],
  			"genre": ["Comedy", "Horror"],
  			"year": 1984,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "PG",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
		},
  		{
  			"id": 23,
  			"title": "Matrix",
  			"cast": ["Keanu Reeves", "Laurence Fishburne"],
  			"genre": ["Action", "Sci Fi"],
  			"year": 1999,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "R",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
		},
  		{
  			"id": 24,
  			"title": "Beauty and the Beast",
  			"cast": ["Emma Watson", "Dan Stevens"],
  			"genre": ["Family", "Fantasy"],
  			"year": 2017,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "PG",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "Movie"
		},
  		{
  			"id": 25,
  			"title": "The Crown",
  			"cast": ["Claire Foy", "Matt Smith"],
  			"genre": ["Drama", "Biography"],
  			"year": 2016,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-MA",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
		},
  		{
  			"id": 26,
  			"title": "The Boys",
  			"cast": ["Karl Urban", "Jack Quaid"],
  			"genre": ["Action", "Comedy"],
  			"year": 2019 ,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-MA",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
		},
  		{
  			"id": 27,
  			"title": "Cobra Kai",
  			"cast": ["Mary Mouser", "William Zabka"],
  			"genre": ["Action", "Comedy"],
  			"year": 2018 ,
  			"director": "N/A",
  			"duration": "N/A",
  			"rating": "TV-14",
  			"plot": "Description description description description description description description description description description description description description.",
  			"url": "js/posters/poster.jpg",
  			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
  			"type": "TV"
		},
		{
     		"id": 28,
     		"title": "CNN",
     		"cast": ["Wolf Blitzer"],
     		"genre": ["Channel"],
     		"year": 2000,
     		"director": "N/A",
     		"duration": "N/A",
     		"rating": "TV-PG",
     		"plot": "Description description description description description description description description description description description description description.",
     		"url": "js/posters/poster.jpg",
     		"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
     		"type": "TV"
		},
		{
 			"id": 29,
 			"title": "FOX",
 			"cast": ["Tucker Carlson"],
 			"genre": ["Channel"],
 			"year": 2000,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "TV-PG",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		},
		{
 			"id": 30,
 			"title": "NBA TV",
 			"cast": ["Scott Cole"],
 			"genre": ["Channel"],
 			"year": 2005,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "TV-PG",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		},
		{
 			"id": 31,
 			"title": "Home",
 			"cast": ["N/A"],
 			"genre": ["Category"],
 			"year": 2020,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "N/A",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		},
		{
 			"id": 32,
 			"title": "Setting",
 			"cast": ["N/A"],
 			"genre": ["Category"],
 			"year": 2020,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "TV-PG",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		},
		{
 			"id": 33,
 			"title": "DVR",
 			"cast": ["N/A"],
 			"genre": ["Category"],
 			"year": 2020,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "TV-PG",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		},
		{
 			"id": 34,
 			"title": "OnDemand",
 			"cast": ["N/A"],
 			"genre": ["Category"],
 			"year": 2020,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "TV-PG",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		},
		{
 			"id": 35,
 			"title": "Guide",
 			"cast": ["N/A"],
 			"genre": ["Category"],
 			"year": 2020,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "TV-PG",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		},
		{
     		"id": 36,
     		"title": "ESPN",
     		"cast": ["N/A"],
     		"genre": ["Channel"],
     		"year": 2002,
     		"director": "N/A",
     		"duration": "N/A",
     		"rating": "TV-PG",
     		"plot": "Description description description description description description description description description description description description description.",
     		"url": "js/posters/poster.jpg",
     		"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
     		"type": "TV"
		},
		{
 			"id": 37,
 			"title": "Search",
 			"cast": ["N/A"],
 			"genre": ["Category"],
 			"year": 2020,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "TV-PG",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		},
		{
 			"id": 38,
 			"title": "List",
 			"cast": ["N/A"],
 			"genre": ["Category"],
 			"year": 2020,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "TV-PG",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		},
		{
 			"id": 39,
 			"title": "Player",
 			"cast": ["N/A"],
 			"genre": ["Category"],
 			"year": 2020,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "TV-PG",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		},
		{
 			"id": 40,
 			"title": "None",
 			"cast": ["N/A"],
 			"genre": ["Category"],
 			"year": 2020,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "TV-PG",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		},
		{
 			"id": 41,
 			"title": "Unknown",
 			"cast": ["N/A"],
 			"genre": ["Category"],
 			"year": 2020,
 			"director": "N/A",
 			"duration": "N/A",
 			"rating": "TV-PG",
 			"plot": "Description description description description description description description description description description description description description.",
 			"url": "js/posters/poster.jpg",
 			"app": ["Amazon Prime Video","Apple TV","FandangoNOW","Google Play Movies & TV","VUDU"],
 			"type": "TV"
		}
	];